<?php

return [
'imldelivery_login',
'imldelivery_payment_status',
'imldelivery_vals_date_plusminus',
'imldelivery_vals_date_val',
'imldelivery_vals_price_plusminus',
'imldelivery_vals_price_val',
'imldelivery_vals_price_type',
'imldelivery_vals_weight_plusminus',
'imldelivery_vals_weight_val',
'imldelivery_orderstatus_sent',
'imldelivery_orderstatus_pvz',
'imldelivery_orderstatus_done',
'imldelivery_orderstatus_courier',
'imldelivery_orderstatus_refused',
'imldelivery_weight_type',
'imldelivery_weight_default',
'imldelivery_weight_description',
'imldelivery_cityfrom',
'imldelivery_static_form',
'imldelivery_static_price',
'imldelivery_variable_price',
'imldelivery_password',
'imldelivery_sort_order',
'imldelivery_status',
'imldelivery_price_courier_same',
'imldelivery_price_courier_other',
'imldelivery_price_pvz_same',
'imldelivery_price_pvz_other',
'imldelivery_testmode',
'imldelivery_geo_zone_id',
'imldelivery_declareprice',
'imldelivery_sidetype',
'imldelivery_sidetype1',
'imldelivery_sidetype2',
'imldelivery_sidetype3',
'imldelivery_headline_courier_nal',
'imldelivery_headline_courier_bnal',
'imldelivery_headline_pvz_nal',
'imldelivery_headline_pvz_bnal',
'imldelivery_time_api',
'imldelivery_show_after_tomeout',
'imldelivery_timeot_price_courier_nal',
'imldelivery_timeot_price_courier_bnal',
'imldelivery_timeot_price_pvz_nal',
'imldelivery_timeot_price_pvz_bnal',
'imldelivery_hide_courier_nal',
'imldelivery_hide_courier_bnal',
'imldelivery_hide_pvz_nal',
'imldelivery_hide_pvz_bnal',
'imldelivery_count_places',
'imldelivery_fixed_size_1',
'imldelivery_fixed_size_2',
'imldelivery_fixed_size_3',
'imldelivery_rounding',
'imldelivery_rounding_value',
'imldelivery_weight_pack',
'imldelivery_show_postamat',
'imldelivery_complect_check',
'imldelivery_showdate',
'imldelivery_yandex_map',
'imldelivery_remove_db_table',
'imldelivery_customservices',


'imldelivery_headline_cart' ,
'imldelivery_login' ,
'imldelivery_password' ,
'imldelivery_status' ,
'imldelivery_sort_order' ,
'imldelivery_departureCity' ,
'imldelivery_testMode' ,
'imldelivery_calcType' ,

'imldelivery_defaultWeightKg' ,

'imldelivery_defaultLength' ,
'imldelivery_defaultWidth' ,
'imldelivery_defaultHeight' ,
'imldelivery_defaultPlacesCount' ,
'imldelivery_enableFullfilment' ,

'imldelivery_packageCalcType' ,
'imldelivery_defaultGoodWeightKg' ,
'imldelivery_defaultGoodLength' ,
'imldelivery_defaultGoodWidth' ,
'imldelivery_defaultGoodHeight' ,
'imldelivery_addExtraWeightKg' ,
'imldelivery_method_24ko_Name' ,
'imldelivery_method_24_Name' ,
'imldelivery_method_c24ko_Name' ,
'imldelivery_method_c24_Name' ,
'imldelivery_conIMLtimeout' ,
'imldelivery_showIMLDelWhenFailCon' ,
'imldelivery_fail_con_method_24ko_price'  ,
'imldelivery_fail_con_method_24_price' ,
'imldelivery_fail_con_method_c24ko_price' ,
'imldelivery_fail_con_method_c24_price' ,
'imldelivery_enable_method_24ko' ,
'imldelivery_enable_method_24' ,
'imldelivery_enable_method_c24ko' ,
'imldelivery_enable_method_c24' ,
'imldelivery_showDateDelivery' ,
'imldelivery_addDeliveryDateDays' ,
'imldelivery_dpExtraOper' ,
'imldelivery_dpExtraNumber' ,
'imldelivery_dpExtraMeasure' ,
'imldelivery_roundingOper' ,
'imldelivery_roundingMeasure' ,
'imldelivery_enableValuatedAmount' ,
'imldelivery_cdOwnRegionPrice' ,
'imldelivery_cdOtherRegionPrice' ,
'imldelivery_pkOwnRegionPrice' ,
'imldelivery_pkOtherRegionPrice' ,
'imldelivery_yandex_map_apikey',
'imldelivery_deliveryInPickpointType',
'imldelivery_isIncludedDeliveryCost',
'imldelivery_defaultVATRate'
	];